### ISSUE TITLE
Hospedaje de prueba en Heroku

### ISSUE THREAD

**Issue by fabianabarca** [fabianabarca/buses#35]
Llevar el proyecto a Heroku de prueba. Documentar el proceso para hacerlo y habilitar credenciales para poder actualizarlo frecuentemente.

**Comment by jeancahu** [comment]
La complejidad del proyecto requiere una mayor intervención de la infraestructura, principalmente a la hora de implementar GTFS realtime, por ende no considero que este issue siga siendo relevante a este punto. En caso de que aún se planeé implementar esta nube, ignorar y reabrir.
