### ISSUE TITLE
Versión imprimible (o "foto") de los horarios

### ISSUE THREAD

**Issue by fabianabarca** [fabianabarca/buses#48]
Mucha gente prefiere compartir el horario o tenerlo para consulta como una foto (en lugar de visitar la página, quizá por consideración de consumo de datos, o lo que sea), así que sería buena poner esa versión a disposición también. Hay que diseñarla y/o generarla a partir de los datos con, quizá, LaTeX o alguna otra forma de transcripción.

**Comment by jeancahu** [comment]
Este issue está resuleto en https://github.com/fabianabarca/buses/pull/51
